version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - cd app
      - chmod +x ./gradlew
      - ./gradlew shadowJar
  build:
    commands:
      - cd app
      - docker build -t ${ECR_REPO}:${VERSION} .
  post_build:
    commands:
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${ECR_REPO}
      - docker push ${ECR_REPO}:${VERSION}
